import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "../assets/css/theme.css";
import BootstrapClient from "@/utils/bootstrapClient";
import Header from "./components/Header";

export const metadata: Metadata = {
	title: "Gift Affairs",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<BootstrapClient />
				{children}
			</body>
		</html>
	);
}
