import type { Metadata } from "next";
import "./globals.css";
import "../assets/css/cartzilla-icons.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "../assets/css/theme.css";
import BootstrapClient from "@/utils/bootstrapClient";
import AuthProvider from "@/utils/AuthProvider";
import HeaderWrapper from "./components/HeaderWrapper";

export const metadata: Metadata = {
	title: "Gift Affairs",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AuthProvider>
					<BootstrapClient />
					<HeaderWrapper />
					{children}
				</AuthProvider>
			</body>
		</html>
	);
}
